# Generated by Django 4.2.23 on 2025-08-01 04:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Complaint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=200)),
                ('subject', models.CharField(max_length=255)),
                ('message', models.TextField()),
                ('location', models.CharField(blank=True, max_length=255, null=True)),
                ('contact_number', models.CharField(max_length=20)),
                ('date_submitted', models.DateTimeField(auto_now_add=True)),
                ('action_taken', models.BooleanField(default=False)),
                ('action_note', models.TextField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
